name: CI

on:
  pull_request:
    branches: [master, develop]
jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # pin@v2
      
      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint
      
      - name: Check types
        run: npm run check-types
      
      - name: Run tests
        run: npm run test